# Generated by Django 6.0.5 on 2026-06-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='birth_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='birth_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='birth_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedprofile',
            name='birth_tz',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
